### PR TITLE
akka 2.4.2

### PR DESCRIPTION
**Pull request by yous**
Bump [akka](http://akka.io/) to 2.4.2.

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?
- [x] Have you successfully ran `brew tests` with your changes locally?

### CODE REVIEW

**Comment by apjanke** [comment]
Hmmm. Same failure to read test results on Yosemite and El Capitan. Looks like maybe something is producing invalid UTF-8 in its output?

```
Failed to read test report file /Users/brew/Jenkins/prs/version/yosemite/brew-test-bot.xml
org.dom4j.DocumentException: Invalid byte 2 of 4-byte UTF-8 sequence. Nested exception: Invalid byte 2 of 4-byte UTF-8 sequence.
    at org.dom4j.io.SAXReader.read(SAXReader.java:484)
```

Any other maintainers know if we can grab that `brew-test-bot.xml` file to examine it directly without parsing it? Does it persist past the test run?

**Comment by DomT4** [comment]
It'll just "fail" repeatedly. The build itself is fine, otherwise Jenkins would red rather than yellow flag it. This is quite a well known Jenkins issue. The last time it was discussed @mikemcquaid was familiar with it but had forgotten how to hunt/resolve the issue, and given it's only a cosmetic problem we've more or less ignored it since.

**Comment by mikemcquaid** [comment]
@apiri Stuff like that should be resolved by a regex like this: https://github.com/Homebrew/homebrew/blob/6c12be4db8434effc805b16bd6dc96f7c804bef2/Library/Homebrew/cmd/test-bot.rb#L920-L921

I'm 100% sure there's a better way of doing this so if you felt like it I'd be very grateful (you seem to be good at similar ratholes :grinning:)

**Comment by xu-cheng** [comment]
> I'm 100% sure there's a better way of doing this so if you felt like it I'd be very grateful (you seem to be good at similar ratholes :grinning:)

**Comment by xu-cheng** [comment]
> I'm 100% sure there's a better way of doing this so if you felt like it I'd be very grateful (you seem to be good at similar ratholes :grinning:)

Yes, there is. According to http://stackoverflow.com/a/28152666 and http://stackoverflow.com/a/14323524, we should filter string based on XML spec. i.e.

```ruby
output = step.output.gsub(/[^\x09\x0A\x0D\x20-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]/, "")
```

**Comment by apiri** [comment]
@mikemcquaid you got the wrong ap*! :) I think he is far better at those problems than myself.

**Comment by mikemcquaid** [comment]
> Yes, there is. According to http://stackoverflow.com/a/28152666 and http://stackoverflow.com/a/14323524, we should filter string based on XML spec. i.e.

@xu-cheng could you try a PR for that? Seems like the idea solution :+1:

**Comment by mikemcquaid** [comment]
@apiri sorry!

**Comment by UniqMartin** [comment]
@yous, what's the status here? Akka 2.4.4 seems to be out by now and I suspect we're better off creating a new pull request in [Homebrew/homebrew-core](https://github.com/Homebrew/homebrew-core), right?

(The Jenkins issues that had previously plagued this PR should be resolved by now.)

**Comment by yous** [comment]
@UniqMartin Thanks for the bump. I made a new pull request https://github.com/Homebrew/homebrew-core/pull/790, so closing this.

**Comment by UniqMartin** [comment]
@yous Awesome, thanks!

**Pull request closed without merging**
