### PR TITLE
diagnostic: prefer guard clauses for readability

### PR DESCRIPTION
**Pull request by UniqMartin**
Guard clauses instead of if/unless blocks make the checks easier to understand and reduce nesting, thus improving overall readability.

This is obviously just a small subset of checks that I converted to demonstrate my point and to gauge whether a change like this would see enough support. I also noticed that we're somewhat inconsistent when dealing with heredocs (mostly with respect to indentation). Do we have a preferred style that should be applied if we decide to go with this change? (So far I avoided changing the indentation unnecessarily.)

My personal preference would be (outdented one level, if there's no conditional)

```ruby
if condition
  <<-EOS
    [text]
  EOS
end
```

but I also saw

```ruby
if condition then <<-EOS
  [text]
EOS
end
```

and

```ruby
if condition
  <<-EOS
  [text]
EOS
end
```

and

```ruby
if condition
<<-EOS
[text]
EOS
end
```

where the latter two have particularly strange indentation (I think).

### CODE REVIEW

**Comment by mikemcquaid** [comment]
:+1: I always prefer early returns

**Comment by bfontaine** [comment]
:+1: for early returns and for the first heredocs snippet.

**Comment by UniqMartin** [comment]
I'm almost shocked by the instant support. :wink: I'll wait a bit if there are other opinions, and if there's no major opposition will go through the remaining checks and adapt them (including heredoc indentation).

**Comment by DomT4** [comment]
:+1:

**Comment by apjanke** [comment]
:+1: for early returns, and for the first two heredoc styles over the latter two.

**Comment by UniqMartin** [comment]
I'm sorry for the long delay! I now updated this PR to apply the above style and indentation changes (and other minor tweaks) to all of the check methods in `diagnostic.rb`. (Unfortunately, the diff no longer displays here on GitHub due to the many changes throughout the file. Not sure how to best handle this.)

**Comment by mikemcquaid** [comment]
> Unfortunately, the diff no longer displays here on GitHub due to the many changes throughout the file. Not sure how to best handle this.

I trust you to just ship this if you've tested it locally.

**Comment by UniqMartin** [comment]
Closing in favor of Homebrew/brew#49 as this no longer cleanly applies in the new repository.

**Pull request closed without merging**
