### PR TITLE
scriptcs 0.16.0

### PR DESCRIPTION
**Pull request by glennblock**
scriptcs 0.16.0

### CODE REVIEW

**Comment by apjanke** [comment]
The updated URL is 404.

```
$ wget https://github.com/scriptcs/scriptcs/archive/v0.16.0.tar.gz
--2016-04-03 03:37:21--  https://github.com/scriptcs/scriptcs/archive/v0.16.0.tar.gz
Resolving github.com... 192.30.252.121
Connecting to github.com|192.30.252.121|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/scriptcs/scriptcs/tar.gz/v0.16.0 [following]
--2016-04-03 03:37:21--  https://codeload.github.com/scriptcs/scriptcs/tar.gz/v0.16.0
Resolving codeload.github.com... 192.30.252.162
Connecting to codeload.github.com|192.30.252.162|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-04-03 03:37:21 ERROR 404: Not Found.
```

Looks like there are tagged releases [hosted on GitHub now](https://github.com/scriptcs/scriptcs/releases). Maybe you could use https://github.com/scriptcs/scriptcs/archive/0.16.0.tar.gz?

**Comment by glennblock** [comment]
Yup that works. I will resend, thanks!

**Comment by glennblock** [comment]
Done!

**Comment by apjanke** [comment]
Thanks!

It'll take a while to make it through the CI build queue tonight; we have a bit of a backlog due to earlier issues. Check back in a few hours.

**Comment by glennblock** [comment]
Awesome, thanks @apjanke!

**Comment by glennblock** [comment]
For those that are interested, here are the release notes: https://github.com/scriptcs/scriptcs/releases/tag/0.16.0

**Comment by glennblock** [comment]
Hey @apjanke anything I need to do here?

**Comment by glennblock** [comment]
Do I need to pull down the latest?

**Comment by apjanke** [comment]
Hmm. Looks like the CI build didn't go. I'll try it again...

@BrewTestBot test this please

**Comment by glennblock** [comment]
Thanks!

**Comment by apjanke** [comment]
Worked this time.

Merged. Thank you for your contribution to Homebrew!

For future reference, minor fixes like that URL fix can just be added to the existing commit in the PR with `git commit --amend` or `rebase -i`. Keeps the commit history tidy (we get a lot of volume). I squashed it while merging, so no need to do anything here.

**Comment by glennblock** [comment]
Thanks! Got it!

**Pull request closed without merging**
