### PR TITLE
download_strategy: add flag --force-domain

### PR DESCRIPTION
**Pull request by jainishshah17**
Added new flag --force-domain for Install command which forces to download bottle and non-bottle packages form HOMEBREW_BOTTLE_DOMAIN which has Virtual repo bottles.

### CODE REVIEW

**Comment by mikemcquaid** [comment]
How does this differ from `HOMEBREW_BOTTLE_DOMAIN`?

**Comment by mikemcquaid** [comment]
From #47783:

> If I have my own Virtual Repository bottles which has all packages (bottle & non-bottle) and I want to Download  all packages only from one source (Virtual Repository). I will let that Virtual repo deal how to get non-bottle package and make it available when brew ask to install any of packages.

How would this virtual repository be populated?

**Comment by jainishshah17** [comment]
Artifactory OSS is supporting this kind of repository.

**Comment by mikemcquaid** [comment]
@jainishshah17 Please provide (significantly) more information on how this would work.

**Comment by jainishshah17** [comment]
For example:
we set export HOMEBREW_BOTTLE_DOMAIN=http://localhost:8080/artifactory
Artifactory has Virtual repository bottles.
It works fine when we say  brew install nginx (as its bottle)
```
Downloading http://localhost:8080/artifactory/bottles/nginx-1.8.0.el_capitan.bottle.1.tar.gz
```
but when we say  brew install riak
```
https://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.2/osx/10.8/riak-2.1.2-OSX-x86_64.tar.gz
```
a flag --force-domain (force download from HOMEBREW_BOTTLE_DOMAIN)for install command which will change download url of non-bottle repository for example Riak From:
```
https://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/osx/10.8/riak-2.1.1-OSX-x86_64.tar.gz
```
To:
HOMEBREW_BOTTLE_DOMAIN/{tap}/{url from formula without protocol}
```
http://localhost:8080/artifactory/bottles/s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/osx/10.8/riak-2.1.1-OSX-x86_64.tar.gz
```

**Comment by mikemcquaid** [comment]
> Artifactory has Virtual repository bottles.

How does Artifactory download these bottles? Does it need to be prepopulated or can it be done automatically? Also, does it support using HTTPS for all transfers, even ones that were originally HTTP?

**Comment by jainishshah17** [comment]
Artifactory Downloads bottles from "http://homebrew.bintray.com/bottles". Its automatic.
Yes, It support both HTTP and HTTPS transfer.

**Comment by mikemcquaid** [comment]
@jainishshah17 The thing I really don't like in your above example:

> https://s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/osx/10.8/riak-2.1.1-OSX-x86_64.tar.gz
> http://localhost:8080/artifactory/bottles/s3.amazonaws.com/downloads.basho.com/riak/2.1/2.1.1/osx/10.8/riak-2.1.1-OSX-x86_64.tar.gz

You're turning a secure HTTPS connection to an insecure HTTP one.

**Comment by jainishshah17** [comment]
Internally it will be HTTPS call always for getting riak's archive and for Artifactory it can be HTTP or HTTPS based on how user configure it.

**Comment by mikemcquaid** [comment]
I'm unhappy with letting a Homebrew user configure a HTTP Artifactory. I'd be willing to consider accepting this if it only supports HTTPS connections from Homebrew to Artifactory.

**Comment by xu-cheng** [comment]
FWIW, I'm unhappy to make `HOMEBREW_BOTTLE_DOMAIN` to control any non bottle download strategy.

**Comment by mikemcquaid** [comment]
> FWIW, I'm unhappy to make HOMEBREW_BOTTLE_DOMAIN to control any non bottle download strategy.

Yes, good point: we'd need a new name for this such as `HOMEBREW_MIRROR_DOMAIN`.

**Comment by jainishshah17** [comment]
Awesome, It will be great to have HOMEBREW_MIRROR_DOMAIN. We are ok with having artifactory running as HTTPS. In Documentation we will recommend users to have artifactory HTTPS.

**Comment by mikemcquaid** [comment]
> Awesome, It will be great to have HOMEBREW_MIRROR_DOMAIN. We are ok with having artifactory running as HTTPS. In Documentation we will recommend users to have artifactory HTTPS.

@jainishshah17 I'd need it to be a requirement that you cannot use Homebrew with an HTTP Artficatory for this to be merged, sorry.

**Comment by mikemcquaid** [comment]
@jainishshah17 so you build the URL like `https://#{HOMEBREW_MIRROR_DOMAIN}/...`

**Comment by xu-cheng** [comment]
IMHO, this feature seems to be rather unique. Therefore, the question is raised whether we should include it for all of users.

Also the url format as `HOMEBREW_MIRROR_DOMAIN/tap/{url from formula without protocol}` is quite strange for such purpose due to the fact that the url can be arbitrary. In common source code mirror services, for example in Debian or our Homebrew bottles, one would anticipate the url be like `HOMEBREW_MIRROR_DOMAIN/tap/file`. On the other hand, the url format you purposed is quite common in proxy services. So may I ask why cannot you solve your unique setting with normal reverse proxy?

**Comment by mikemcquaid** [comment]
> Also the url format as HOMEBREW_MIRROR_DOMAIN/tap/{url from formula without protocol} is quite strange for such purpose due to the fact that the url from formula can be arbitrary.

Good point; I'd like to see/know how that would handle e.g. git checkouts?

**Comment by xu-cheng** [comment]
As discussed in team chat, I think `HOMEBREW_ARTIFACT_DOMAIN` would be a better name. mirror is too vague term in such circumstance.

**Comment by jainishshah17** [comment]
We are totally fine with HOMEBREW_ARTIFACT_DOMAIN. I will create new PR with this new ENV variable.

**Comment by mikemcquaid** [comment]
@jainishshah17 If you can just modify this PR that'd be better.

**Comment by jainishshah17** [comment]
Anything else you want me to change.

**Comment by MikeMcQuaid** [comment]
@jainishshah17 Apologies for the delays here. Would you mind reopening this on https://github.com/homebrew/brew and we'll continue conversation and get this merged? Thanks and sorry again.

**Pull request closed without merging**
