### PR TITLE
New Tile38 1.0.4 formula

### PR DESCRIPTION
**Pull request by hanxue**

### CODE REVIEW

**Comment by apjanke** [comment]
The failure is just a "too new" audit failure.

```
failed: brew audit tile38 --strict --online
Stacktrace
        Error: 1 problem in 1 formula
==> audit problems
tile38:
 * GitHub repository too new (<30 days old)
```

This is a very young project, just announced a week ago as far as I can tell. You can resubmit this in a month and it will go through. In the meantime, you or tile38 can [set up your own tap](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md) to support installation via `brew`.

**Comment by apjanke** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Calling this mature enough now; there's clearly enough interest on GitHub and it's a solid-looking release. Will merge this once the Jenkins build goes through.

**Comment by apjanke** [comment]
Merged in https://github.com/Homebrew/homebrew-core/commit/d8ee49610ca4abf4ba30f7079cffe59239a63b48.

Thank you for your contribution to Homebrew!

**Comment by hanxue** [comment]
Thanks @apjanke for leaving the PR open rather than asking me to re-submit. Glad that it's merged now.

**Pull request closed without merging**
