### PR TITLE
[WIP] formula renames allow old names

### PR DESCRIPTION
**Pull request by vladshablinsky**
This is a PR for discussing formula-renames and implementing formula renames with old names and multiple renames allowed.
Some ideas were discussed here: https://github.com/Homebrew/homebrew/issues/42965 .

Current structure is the following:

Every time we install formula, we assign the commit when that formula was last changed.
When we rename a ‘name’, we append the following string to `Renames/name`: `newname`, (last commit to the master branch -- `git rev-parse origin/master`)

We can resolve formula starting from specific commit by searching the first successor of that commit in rename file (or the same commit). When we find the successor (or the same commit) we have next name and successor-commit, we continue the same procedure but in the other rename file.

We need to resolve formula at least in these cases:

* We have `name` installed, and some commit assigned to the installed keg. `name` can be renamed and we resolve name from the assigned to `name` keg's commit.
* `brew update` -- we need to reveal formula renames and we resolve names from updater's `initial_commit`.
* `Formulary.factory` -- try to resolve `name` if we can't instantiate formula.

Example:

`HEAD` is `abacaba`
We install `ack` and `abacaba` gets assigned to installed keg.
Somebody renames `ack` and writes `newack, abacaba` to `Renames/ack`, then commits
We pull and have `HEAD` equals to `bbacaba` (just random hash different from `abacaba`)
Let's resolve `ack` from commit `abacaba`. The name is  `newack`.

`FormulaResolver` is the main class and the one I'm working on now. Its purpose is resolving names from rack or specific commit. For now I use files in `Renames` directory that have information about all the renames, but this structure will probably changed and there will be no need in `Renames` file because all the renames will be resolved using only git.

`Migrator` and other things are not ready now and can be completely changed after `FormulaResolver` implemented properly.

TODO
=====
- [ ] switch from `Renames` to git if it's possible
- [ ] update migrator/migrate and other things
- [ ] handle existing renames
- [ ] add formula deletions
- [ ] `cmd/install` and `MigrationNeededError`
- [ ] `cmd/upgade`
- [ ] update `update-report`
- [ ] cache for formula resolver
- [ ] `cmd/fix` to help fixing renames that can be handled automatically
- [ ] dependencies and audit
- [ ] brew doctor
- [ ] `outdated` fix
- [ ] update `pretty_installed` for renames

### CODE REVIEW

**Comment by vladshablinsky** [comment]
I would want some feedback on approach in general and on FormulaResolver for now.
All the other things are not ready yet. Thanks!

**Comment by vladshablinsky** [comment]
I thought about tracking renames with just using git without `Renames` yesterday. It seemed really good until today. I think we've got a big problem with using git for formula resolving at all when we resolve dependencies of some repositories tapped with `--depth=1` option.

Initially I wanted to resolve dependencies like this:
We have a formula `name`, that depends on `dependency` and we know that we resolve `dependency` after the last commit made to `name`. If we want to update `name` formula, we also need to update all the `depends_on` in it's dependencies to be able to handle renames and only then upload formula upstream. But since we can have `--depth=1` option I don't see how it is possible to use `git` to track renames in chronological order.

**Example:** If we tap something with `--depth=1` and try to resolve dependencies for `name`, we resolve them from the last modifying commit to `name` formula and this commit is the first commit in tapped repository, so dependencies get resolved to the same names they present in `name` file. However there can be the case when there is no changes to `name` at all after it is created, but dependencies of `name` get renamed. If we have full git history then we can resolve `name`'s dependencies for that case, otherwise, we can't or at least I can see the way we can do that.

As possible workaround I can see two options:
* Restrict using `--depth=1`.
* Think about the idea of assigning 'timestamps' to each changed/renamed/deleted formula.

Any thoughts @mikemcquaid @xu-cheng?

**Comment by mikemcquaid** [comment]
@vladshablinsky Sorry for the massive delay here. Basically: `--depth=1` shouldn't be a problem because we know if someone doesn't have the old git revisions of a formula then they have never installed it with the old name. I think it's OK to restrict and/or error if Homebrew developers/contributors try to create a formula rename PR with `--depth=1` and tell them to run `git fetch --unshallow`.

**Comment by xu-cheng** [comment]
This PR probably need to wait after core/formula separation, since the git sha1 will be changed.

**Comment by vladshablinsky** [comment]
@mikemcquaid I think we didn't understand each other.

>Basically: --depth=1 shouldn't be a problem because we know if someone doesn't have the old git revisions of a formula then they have never installed it with the old name. 

Absolutely agree with that, but I don't see the way how we can hadle this case:

```
                    1 |               2 |                   3 |
----------------------|-----------------|---------------------|
(b that depends on a) |                 |                     |
                      |   a ------> b   |                     |
                      |                 |   introduce new a   |

```

We can resolve `b`'s dependency at each point if we have all the commits.

Now let's take a look if we have a shallow repository (one described above, but squeezed):

```
                    3 |
----------------------|
(b that depends on a) |
          b           |
   introduce new a    |
```

All our changes are made in one place, so we can't resolve `b`'s dependency.

> I think it's OK to restrict and/or error if Homebrew developers/contributors try to create a formula rename PR with --depth=1 and tell them to run git fetch --unshallow.

I think it won't break anything, because we only need that there is no renames between contributor's `master` and `origin/master`.

**Comment by mikemcquaid** [comment]
@vladshablinsky This is only a problem for third-party taps, right, because in core we can just mandate the dependencies be renamed, right? I think in that case it could be fine to just always assume the new `a` if we don't have the necessary history. Another option is that after we've migrated the core formula repository we disable shallow cloning of it and/or taps in future CC @xu-cheng for thoughts.

**Comment by vladshablinsky** [comment]
> because in core we can just mandate the dependencies be renamed, right?

@mikemcquaid you mean either restrict renaming formulae if something depends on or if we eventually rename the formula we need to rename it's name in all the formulae that depend on it?

> Another option is that after we've migrated the core formula repository we disable shallow cloning of it and/or taps in future

I think this approach is much more flexible.

**Comment by mikemcquaid** [comment]
> @mikemcquaid you mean either restrict renaming formulae if something depends on it ot if we eventually rename the formula we need to rename its name in all the formulae that depend on it?

Either could work but I guess the prior is more friendly to taps.

> I think this approach is much more flexible.

🆒

**Comment by MikeMcQuaid** [comment]
@vladshablinsky Would you mind reopening this on https://github.com/homebrew/brew and we'll continue conversation there? Thanks!

**Pull request closed without merging**
