### PR TITLE
Remove formulae/aliases/travis.yml.

### PR DESCRIPTION
**Pull request by MikeMcQuaid**
CC @xu-cheng

### CODE REVIEW

**Comment by xu-cheng** [comment]
I need to do some test for this, but I think it should be fine.

**Comment by MikeMcQuaid** [comment]
Thanks. Feel free to merge when done testing.

**Comment by MikeMcQuaid** [comment]
@xu-cheng Thanks for testing/merging.

**Comment by MikeMcQuaid** [comment]
@xu-cheng Actually, mind detailing your testing steps so I can do so for future file removal/upgrade testing? No rush on that.

@Homebrew/maintainers This repository now has no pull requests and no formulae (so it should hopefully stay that way). There's no way to disable PRs on a repository but we can feel free to insta-close any future ones.

**Comment by UniqMartin** [comment]
> This repository now has no pull requests and no formulae (so it should hopefully stay that way). There's no way to disable PRs on a repository but we can feel free to insta-close any future ones.

Hopefully it will. There were actually fewer than I had expected since we split. It's looking almost too empty now. —*Looking for, but failing to find a tumbleweed emoji.*

**Comment by xu-cheng** [comment]
> Actually, mind detailing your testing steps so I can do so for future file removal/upgrade testing? No rush on that.

`brew update-test --commit=<sha>`. I used the sha obtained from https://travis-ci.org/xu-cheng/homebrew-test/builds/120408105, i.e., the commit in various Travis CI images.

**Comment by MikeMcQuaid** [comment]
@xu-cheng Cool, thanks. What commit do you checkout before running that test?

**Comment by xu-cheng** [comment]
The latest commit, that is the commit that `brew update-test` will try to update it to.

**Comment by MikeMcQuaid** [comment]
@xu-cheng So: the checked out latest commit in this PR, latest commit in `Homebrew/brew`'s `master` or latest commit in this repo?

**Comment by xu-cheng** [comment]
latest commit in this PR.

**Comment by xu-cheng** [comment]
Also, `brew update-test` will show:
```
$ brew update-test
Start commit: foo
End   commit: bar
```

Which means it will try to test update homebrew from commit foo to bar.

**Comment by MikeMcQuaid** [comment]
@xu-cheng Great, thanks.

**Pull request merged**
