### PR TITLE
Upgrade typesafe-activator.rb to 1.3.9, change to lightbend

### PR DESCRIPTION
**Pull request by wsargent**

### CODE REVIEW

**Comment by DomT4** [comment]
Presume the install stages need reworking for the new name as well:
```
==> Verifying typesafe-activator-1.3.9.zip checksum
unzip /Library/Caches/Homebrew/typesafe-activator-1.3.9.zip
Archive:  /Library/Caches/Homebrew/typesafe-activator-1.3.9.zip
   creating: activator-1.3.9-minimal/
   creating: activator-1.3.9-minimal/bin/
  inflating: activator-1.3.9-minimal/bin/activator.bat  
  inflating: activator-1.3.9-minimal/bin/activator  
   creating: activator-1.3.9-minimal/libexec/
  inflating: activator-1.3.9-minimal/libexec/activator-launch-1.3.9.jar  
Error: No such file or directory - /usr/local/Cellar/typesafe-activator/1.3.9/libexec/activator
```

**Comment by wsargent** [comment]
@DomT4 it looks like the zip file now has the "activator-1.3.9-minimal/bin" and "activator-1.3.9-minimal/libexec" instead of just the plain directory.  I don't know how to swizzle the libexec/bin paths so they work out.

**Comment by mikemcquaid** [comment]
@wsargent You'll need to try and edit the `install` method. https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md may help.

**Comment by wsargent** [comment]
@mikemcquaid I am completely lost.  I read through https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#just-moving-some-files and tried various combinations of "install" but it's not going where I expect.  Where's the canonical documentation for the method?

**Comment by mikemcquaid** [comment]
@wsargent I'm afraid that's the best we have. Can you commit what you were trying to do (even if it doesn't work at all) and then I'll offer some help from there? Thanks!

**Comment by UniqMartin** [comment]
This has been updated to 1.3.10 in Homebrew/homebrew-core#747. Closing because of this.

**Pull request closed without merging**
