### PR TITLE
Conan 0.8.5

### PR DESCRIPTION
**Pull request by lasote**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by dunn** [comment]
Looks like it needs to be rebased against `origin/master`.

**Comment by lasote** [comment]
Done. I always rebase but I suppose since this morning it got outdated.

**Comment by tdsmith** [comment]
Some of the resources look stale; gonna follow this up.

**Comment by lasote** [comment]
Whats the problem? Can I do something?

**Comment by tdsmith** [comment]
Some of the bundled dependencies are a little stale and I wanted to see if they were pinned and if the pinned versions were acceptable; I think we're good. Thanks for the submission!

**Pull request closed without merging**
