### PR TITLE
kobalt 0.720

### PR DESCRIPTION
**Pull request by cbeust**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by tdsmith** [comment]
Thanks for your pull request! :tada: Homebrew thrives because of contributions like this one.

**Comment by cbeust** [comment]
Thanks @tdsmith.

Did I make the commit in the wrong repo?

**Comment by tdsmith** [comment]
Nope! We split the repos since you sent this PR, so it was in the right place. PRs should land against homebrew-core in the future. :)

**Comment by cbeust** [comment]
That’s what I suspected, will send my PR’s to homebrew-core next time.
Thanks!
​

-- 
Cédric

**Pull request closed without merging**
