### PR TITLE
Add support to luarocks to luajit, code adapted from lua formula

### PR DESCRIPTION
**Pull request by archiloque**

### CODE REVIEW

**Comment by DomT4** [comment]
You can't use this style without creating a conflict with the `lua` formula. You'll need to adapt it more fully. Last time I checked locally it refused to take `--lua-suffix=jit` as a valid argument.

**Comment by archiloque** [comment]
- what should I adapt, renaming the execs to luarocksjit ?
- I tried lua-suffix locally and it worked, you can see it used in luarock's  configure file

**Comment by DomT4** [comment]
> what should I adapt, renaming the execs to luarocksjit 

Yes. Something like this.

> I tried lua-suffix locally and it worked, you can see it used in luarock's configure file

Sorry, I meant the `"--lua-version=5.2"` argument wouldn't take anything aside a number, but the problem is that we can't give it a real number because `5.1`, `5.2` and `5.3` are already in use and if we re-use them it'll introduce conflict.

**Comment by archiloque** [comment]
How is used LUA_VERSION beside the configuration ? I don't know enough about luarocks' internals to understand where a conflict may appear.

**Comment by xpol** [comment]
It would be wonderful if luarocks install with luajit.

**Comment by garthk** [comment]
@xpol et al, you can use `luarocks-5.1` from `lua51` with `luajit`:

```
brew install lua51
eval `luarocks-5.1 path --bin`
luarocks-5.1 install socket
luajit -r 'require "socket"; print(socket)'
```

**Comment by bfontaine** [comment]
Ping?

**Comment by apjanke** [comment]
Closing this due to inactivity/lack of response.

**Pull request closed without merging**
