### PR TITLE
diff-so-fancy 0.7.1

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by dunn** [comment]
The test is failing:
```
==> /usr/local/Cellar/diff-so-fancy/0.7.1/bin/diff-so-fancy
tput: No value for $TERM and no -T specified
tput: No value for $TERM and no -T specified
/usr/local/Cellar/diff-so-fancy/0.7.1/bin/diff-so-fancy: line 43: let: width=: syntax error: operand expected (error token is "=")
/usr/local/Cellar/diff-so-fancy/0.7.1/bin/diff-so-fancy: line 43: let: width=: syntax error: operand expected (error token is "=")
/usr/local/Cellar/diff-so-fancy/0.7.1/bin/diff-so-fancy: line 55: /usr/local/Cellar/diff-so-fancy/0.7.1/lib/diff-so-fancy.pl: No such file or directory

**Comment by stevemao** [comment]
@scottchiefbaker could you have a look on this? Thanks.

**Comment by scottchiefbaker** [comment]
What/where is that test failing? Looking at line 43 of the bash d-s-f that's a pretty standard `tput` call. It's just shelling out to `tput` to count the width of the terminal. My guess is that whatever terminal your running the tests in isn't setting the `$TERM` environment variable so `tput` doesn't know how to count the columns?

The `-T` option on `tput` lets you force the terminal type, but you shouldn't need to do that. My guess is misconfigured terminal.

**Comment by dunn** [comment]
Oh, then `ENV["TERM"] = "xterm"` at the top might be all that's necessary.

**Comment by scottchiefbaker** [comment]
@dunn that would make sense to me... but your terminal should already be setting that.

**Comment by tdsmith** [comment]
cf. https://github.com/Homebrew/homebrew-core/pull/58

**Comment by mikemcquaid** [comment]
@scottchiefbaker It's running in Jenkins CI so it's going to have a weird terminal setting there.

**Comment by scottchiefbaker** [comment]
Any good CI should be running a legit terminal that sets the appropriate variables, that seems weird to me. But if manually setting `$TERM` works then great.

**Comment by UniqMartin** [comment]
Closing this in favor of Homebrew/homebrew-core#58.

**Pull request closed without merging**
