### PR TITLE
Prevent `brew deps` crash when ARGV only contains casks

### LINKED ISSUE #48949: deps doesn't work on Caskroom/...
Is this expected not to work?

    % brew deps Caskroom/cask/java
    Error: undefined method `map' for nil:NilClass
    Please report this bug:
        https://git.io/brew-troubleshooting
    /usr/local/Library/Homebrew/cmd/deps.rb:28:in `deps'
    /usr/local/Library/brew.rb:85:in `<main>'

At the very least, it probably shouldn't throw an un-handled error.

Here's my `brew config`.

    HOMEBREW_VERSION: 0.9.5
    ORIGIN: https://github.com/Homebrew/homebrew
    HEAD: b369c25d3ec6dcaaed86c2d05364ae1ca80786f4
    Last commit: 8 hours ago
    HOMEBREW_PREFIX: /usr/local
    HOMEBREW_REPOSITORY: /usr/local
    HOMEBREW_CELLAR: /usr/local/Cellar
    HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
    CPU: 12-core 64-bit ivybridge
    OS X: 10.11.3-x86_64
    Xcode: N/A
    CLT: 7.2.0.0.1.1447826929
    Clang: 7.0 build 700
    X11: N/A
    System Ruby: 2.0.0-p645
    Perl: /usr/bin/perl
    Python: /usr/bin/python
    Ruby: /usr/bin/ruby =>
    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
    Java: N/A

### PR DESCRIPTION
**Pull request by ilovezfs**
Closes #48949

### CODE REVIEW

**Comment by xu-cheng** [comment]
How about changing `ARGV.named.empty?` to `ARGV.formulae.empty?` which seems to be a better solution?

Another thing is we probably should check other brew commands to see if they have the same symptoms when passing cask as argument. 

:+1: for this PR

**Comment by ilovezfs** [comment]
@xu-cheng Yes, that may be a better solution. However, it can lead to misleading output. Casks can indeed have dependencies. Simply skipping them suggests to the user that all dependencies have been listed when really only the formulae dependencies have been listed.

**Comment by ilovezfs** [comment]
OK, checking other commands:

1) `desc`, `homepage`, `missing`, `options`, `pin`, `unpack` just skip it (so there's precedent for your solution @xu-cheng). When it's the only argument, `desc` exits without comment; `homepage` gives a usage error; `missing` exits without comment ; `options` exits without comment; `pinned` exits without comment as if it did something but it didn't, at least not according to `brew list --pinned`; `unpack` prompts for a formula argument
2) `brew bottle` and `brew cleanup` just exit without comment as if they did something, or skip it if formulae are listed too
3) `brew cat` skips it even though it's not supposed to support multiple arguments
4) `brew create` proceeds with the basename
```
bash-4.3$ brew create Caskroom/cask/java
Formula name [java]: 
```
5) `brew info` is order dependent
```
bash-4.3$ brew info Caskroom/cask/java rsync
Error: No available formula with the name "caskroom/cask/java" 
bash-4.3$ brew info rsync Caskroom/cask/java 
homebrew/dupes/rsync: stable 3.1.2
Utility that provides fast incremental file transfer
https://rsync.samba.org/
/usr/local/Cellar/rsync/3.1.2 (8 files, 758.4K) *
  Built from source
From: https://github.com/Homebrew/homebrew-dupes/blob/master/rsync.rb
==> Dependencies
Build: autoconf ✔

Error: No available formula with the name "caskroom/cask/java" 
bash-4.3$
```
6) `brew list` doesn't check the type
```
bash-4.3$ brew list Caskroom/cask/java
Error: No such keg: /usr/local/Cellar/java
```
7) `brew style` checks everything in the working directory recursively and will just keep going until you realize you should cancel it, at which point you get:
```
bash-4.3$ 
Exiting... Interrupt again to exit immediately.
```
8) `brew uses` seems to dump everything in sight:
```
bash-4.3$ brew uses Caskroom/cask/java | wc -l
    4539
```
Am I the only one thinking that ANY mention of a cask should be an error unless the command is actually `brew cask ...`

**Comment by ilovezfs** [comment]
@xu-cheng PR refreshed with your proposal.

**Comment by UniqMartin** [comment]
I think in this PR we can focus on the specific failure and the currently implemented fix looks good to me.

Thanks for your detailed analysis, @ilovezfs! I agree that it isn't ideal how we treat casks with most of our commands. That can be mostly attributed to our somewhat simple argument handling, where we usually only pick arguments as needed, but don't check exhaustively whether *all* of them make sense in the current context. (Something that is on our agenda and that we want to improve in the future.)

Then again I'd say it is somewhat naive to call `brew` commands (instead of `brew cask` commands) on casks and to expect them to simply work, given that casks are completely unrelated to formulae. Or am I naively assuming some understanding most of our users don't have and/or don't care about?

It would be cool if you could address some of the worst behaviors from the list you compiled in separate PRs (one per command), preferably in a way that is minimally invasive, but significantly improves the user experience. What do you think about this idea?

**Comment by ilovezfs** [comment]
@UniqMartin I'm having trouble imagining any use case for using brew commands on casks. Are there any? So it seems like the simplest answer to throw an error immediately if any argument is a cask and the subcommand isn't `brew cask`.

**Comment by UniqMartin** [comment]
> I'm having trouble imagining any use case for using brew commands on casks. Are there any?

Personally, I agree. The only use I could find is `brew install` and [here's the code that deals with casks](https://github.com/Homebrew/homebrew/blob/c3438ae77441c606e75b1c3697589588177f75ad/Library/Homebrew/cmd/install.rb#L28-L39). Not sure what this integration gives us, but I also haven't researched why this was added. However, now that it's there, we can't easily remove it again.

> So it seems like the simplest answer is to throw an error immediately if any argument is a cask and the subcommand isn't `brew cask`.

… or `brew install`. I tend to agree. I'm just a bit hesitant littering the prologue of all internal commands with something like `odie "You shall invoke 'brew cask'." unless ARGV.casks.empty?`, but I also don't want to block this completely as I don't want to impact a tap- or user-provided external command that legitimately might deal with both casks and formulae. (I'm hoping another maintainer voices their opinion on this topic.)

**Comment by mikemcquaid** [comment]
Eventually we're planning on integrating Cask and Homebrew more closely so that more of these sort of things are supported. Not sure what's best for now, though

**Comment by apjanke** [comment]
We've accepted a GSoC project for Cask integration. Want to just close this out and let our student work it out?

**Comment by ilovezfs** [comment]
sure

**Pull request closed without merging**
