### PR TITLE
rabbitmq: build from source

### PR DESCRIPTION
**Pull request by mistydemeo**
I've tested that the server launches, but I'd like to do more thorough testing before merging.

### CODE REVIEW

**Comment by asparagui** [comment]
+1 on just merging this.

**Comment by mikemcquaid** [comment]
Yeh, agreed.

**Comment by bfontaine** [comment]
Any update on that?

**Comment by michaelklishin** [comment]
This looks OK to me. What's the point of building from source? If it's OpenSSL, that's an Erlang runtime dependency, not RabbitMQ's.

**Comment by mikemcquaid** [comment]
@michaelklishin For a secure OpenSSL. What you've said is not actually the case as our Erlang formula doesn't link against OpenSSL.

**Comment by michaelklishin** [comment]
@mikemcquaid my point was that RabbitMQ itself does not link against OpenSSL. However, I've forgotten that the Homebrew formula these days embeds Erlang. In which case I'd use the regular generic UNIX tarball. There is still no reason to build from source.

**Comment by mikemcquaid** [comment]
@michaelklishin I see. Any chance you could try and submit a pull-request to sort this out? Currently it's a fairly bad security issue for Homebrew RabbitMQ users.

**Comment by xu-cheng** [comment]
Ping. Building from source is demanded in  #40377 and #43151

**Comment by mikemcquaid** [comment]
@mistydemeo Mind rebasing/merging this (or me doing so)?

**Comment by bfontaine** [comment]
Ping?

**Comment by apjanke** [comment]
Closing this out: we're clearing out legacy-homebrew, and I think we've established that pure-Java packages are an exception to the "build everything from source" rule, and acceptable to use the "binary" bytecode distributions of. As I understand it from these comments and examining the formula, RabbitMQ depends on Erlang which uses OpenSSL, but it does not link to anything itself or use JNI, so it counts as pure-Java for these purposes. `brew linkage` agrees.

```
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$ brew linkage rabbitmq
[/usr/local/Library/Taps/homebrew/homebrew-core on ⇄ master]
$
```

If I'm wrong about that, please re-open on the new homebrew/core repo.

**Pull request closed without merging**
