### PR TITLE
Option to keep Rust src for racer

### PR DESCRIPTION
**Pull request by CamJN**

### CODE REVIEW

**Comment by apjanke** [comment]
Could you rebase and squash these to a single commit? The "merge branch 'master'" commit looks like it's an intermediate bookkeeping commit, and shouldn't show up in the main commit history.

Here's the failure on Jenkins.

```
==> make
/usr/bin/python src/etc/dl-snapshot.py x86_64-apple-darwin
running: curl -o target/dl/cargo-nightly-x86_64-apple-darwin.tar.gz https://static.rust-lang.org/cargo-dist/2015-04-02/cargo-nightly-x86_64-apple-darwin.tar.gz
extracting cargo-nightly-x86_64-apple-darwin/cargo/manifest.in
extracting cargo-nightly-x86_64-apple-darwin/cargo/share/zsh/site-functions/_cargo
extracting cargo-nightly-x86_64-apple-darwin/cargo/share/man/man1/cargo.1
extracting cargo-nightly-x86_64-apple-darwin/cargo/share/doc/cargo/LICENSE-APACHE
extracting cargo-nightly-x86_64-apple-darwin/cargo/share/doc/cargo/LICENSE-MIT
extracting cargo-nightly-x86_64-apple-darwin/cargo/share/doc/cargo/LICENSE-THIRD-PARTY
extracting cargo-nightly-x86_64-apple-darwin/cargo/share/doc/cargo/README.md
extracting cargo-nightly-x86_64-apple-darwin/cargo/etc/bash_completion.d/cargo
extracting cargo-nightly-x86_64-apple-darwin/cargo/bin/cargo
touch target/snapshot/bin/cargo
/usr/local/Cellar/rust/1.6.0/bin/rustc -V
rustc 1.6.0
target/snapshot/bin/cargo --version
cargo 0.0.1-pre-nightly (84d6d2c 2015-03-31) (built 2015-04-01)
target/snapshot/bin/cargo build --target x86_64-apple-darwin --release  
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading winapi-build v0.1.1
 Downloading libc v0.2.4
 Downloading rand v0.3.13
 Downloading miniz-sys v0.1.7
 Downloading env_logger v0.3.2
 Downloading strsim v0.3.0
 Downloading flate2 v0.2.11
 Downloading uuid v0.1.18
 Downloading libgit2-sys v0.3.8
Unable to get packages from source

To learn more, run the command again with --verbose.
make: *** [cargo-x86_64-apple-darwin] Error 101
```

Don't know if this is a transient connectivity failure or something else.

Is the "pre-nightly" version of `cargo` expected?

**Comment by apjanke** [comment]
I dunno if a `--with-src` option is the right way to do this. It feels excessive to require a heavyweight formula like Rust to be built from source just to install some additional files from the distribution.

Linux package managers and Java distributions tend to have separate `foo-src` packages to install the source code for something.  Maybe we should have a separate `rust-src` formula to install this. Or if the source directory tree isn't too big, just include it unconditionally.

**Comment by DomT4** [comment]
I kind of worry about opening the floodgates on this. We've turned down various offers of ways to keep the source/build directory around before now, often on the basis they require too much formula hacking, and this doesn't really feel any different.

**Comment by apjanke** [comment]
Have a look at the [install instructions for Racer](https://github.com/phildawes/racer#from-sources), which include a "download the Rust source" step. If the reason to keep the source around is to support Racer, it might make more sense to just vendor the Rust source as a resource during the Racer install, perhaps as part of a new `racer` Homebrew formula, if that's appropriate. Duplicating the Rust source between formulae that use it could be less of a pain than adding an option that triggers build-from-source in `rust` itself. 

Though I think a separate `rust-src` package could still make sense. It's sort of a different product/package than the Rust toolchain binaries, as long as it has a standard distribution form.

**Comment by CamJN** [comment]
I dunno, I was just implementing the suggestion from https://github.com/Homebrew/homebrew/pull/44700#issuecomment-167297860. I personally think that racer should just grab the right sources for the installed rust using something like the following, but I already know it's not allowed.
```
resource "rust-src" do
    url Formula['rust'].stable.url
    sha256 Formula['rust'].stable.checksum.hexdigest
end
```

**Comment by DomT4** [comment]
> it might make more sense to just vendor the Rust source as a resource during the Racer install, perhaps as part of a new racer Homebrew formula, if that's appropriate.

I would prefer this option, personally.

**Comment by apjanke** [comment]
> I would prefer this option, personally.

Yeah, especially if `racer` is going to be installed by `cargo` and not Homebrew. Looking at that comment, it sounds like they're expecting to manage `racer` and similar Rust programs with `cargo` as an alternative to Homebrew?

**Comment by CamJN** [comment]
They are not, `cargo install` is not meant to be the beginnings of a package manager and doesn't have any way of pulling down dependencies like the rust source.

**Comment by CamJN** [comment]
Closing b/c newer rust in homebrew-core

**Pull request closed without merging**
