### PR TITLE
macvim: disable ruby integration on 10.6

### PR DESCRIPTION
**Pull request by rhendric**
Per discussion in #38047

### CODE REVIEW

**Comment by DomT4** [comment]
It's probably worth adding a note above the line to the issue referenced so someone doesn't attempt to reverse it later.

**Comment by rhendric** [comment]
Good idea, done.

**Comment by jacknagel** [comment]
Is this correct? I thought the problem was a mismatch caused by a non-system ruby being in the PATH, and macvim's configure subsequently making invalid assumptions about the system ruby?

**Comment by rhendric** [comment]
I tried brewing macvim after a `brew unlink ruby` and got the same compilation error as before, so I don't think that's it.

**Comment by jacknagel** [comment]
As far as I can tell, nobody ever posted full logs from a failed build *without* a non-system ruby installed. I'd like to see that before pulling something like this.

Note that for vim, we also need the file `src/auto/config.log` from the failed build, to get the actual configure log.

**Comment by rhendric** [comment]
`brew gist-logs`: https://gist.github.com/anonymous/7b7ba534a056ec21203d
`src/auto/config.log`: https://gist.github.com/rhendric/bd05f7345fc581cd075c

**Comment by jacknagel** [comment]
Can you try `brew install vim --env=super` and gist the resulting logs?

**Comment by rhendric** [comment]
With or without Homebrew's ruby linked?

**Comment by rhendric** [comment]
Oh, and did you mean `vim` or `macvim`?

**Comment by jacknagel** [comment]
Sorry, `macvim`.

wrt ruby, the same conditions as however the above logs were generated.

**Comment by rhendric** [comment]
`brew gist-logs`: https://gist.github.com/16cefe6952bffdc3df95
`src/auto/config.log`: https://gist.github.com/ce63e002fad7a25a97b6

**Comment by jacknagel** [comment]
Well, configure is detecting the header directory as:

```
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/universal-darwin10.0
```

This is basically how configure decides this:

```sh
ruby -r mkmf -e "print RbConfig::CONFIG['rubyhdirdir'] || RbConfig::CONFIG['archdir']"
```

It seems that this may be falling back to `archdir` which is not correct. `rubyhdrdir` must not be defined.

On 10.10 this returns

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0
```

which is a much more reasonable thing.

**Comment by rhendric** [comment]
Hmm, okay.

So, you're right: `/usr/bin/ruby -r mkmf -e "print RbConfig::CONFIG['rubyhdrdir']"` returns `nil` for me. Googling indicates that `rubyhdrdir` was added in Ruby 1.9, and Snow Leopard ships with 1.8.7, so this makes sense.

Inspired by that, I tried a few things and this is the only combination that gets `--enable-rubyinterp` to work for me so far:
* Adding a `depends_on :ruby => "1.9"`
* `brew unlink ruby` before compiling
* Running in std env (as currently specified in the formula)

I tried commenting out the `env :std` line in the hopes that superenv would protect me from a linked ruby, but that failed. (It's looking for a nonexistent `/Developer/Library/Xcode/PrivatePlugIns/Xcode3Core.ideplugin/Contents/SharedSupport/Developer/Library/Xcode/Plug-ins/LLVM GCC 4.2.xcplugin/Contents/Resources/llvm-gcc` file... good grief.)

Thoughts on next things to try? Unlinking ruby is annoying; if it weren't for that I'd just slap a `depends_on :ruby => ["1.9", :recommended] if MacOS.version <= :snow_leopard` in there and be done.

**Comment by jacknagel** [comment]
I think probably any breakage in configuring vim against ruby 1.8 is unintentional, but a good first step would be to confirm that with upstream (vim, as I assume that macvim is not modifying this code) and then get a fix in place on that side.

**Comment by bfontaine** [comment]
Anything new on this?

**Comment by rhendric** [comment]
Upstream has decided to stop supporting compiling on 10.6, so I suppose this is dead. :crying_cat_face:

**Pull request closed without merging**
