### PR TITLE
llvm 3.7.1

### PR DESCRIPTION
**Pull request by DennisOSRM**
Pretty straight-forward update of the Formula to reflect the latest llvm release.

### CODE REVIEW

**Comment by DomT4** [comment]
We're stuck on a few upstream projects not being compatible yet: #47824

You can check those if you wish to. The other PR seems to have gone silent.

**Comment by chriso** [comment]
Any update on this? `3.8.0` is now available: http://llvm.org/releases/

**Comment by mikemcquaid** [comment]
@chriso If there's any updates they'd be posted in the PR.

**Comment by mikemcquaid** [comment]
@BrewTestBot test this please

**Comment by apjanke** [comment]
Closing this as obsolete.

Feel free to re-submit 3.8 or later over on the new homebrew/core repo.

**Pull request closed without merging**
