### PR TITLE
beanstalkd: rename from beanstalk

### PR DESCRIPTION
**Pull request by vladshablinsky**
Needs to be merged when the bug is fixed. https://github.com/Homebrew/homebrew/issues/42965

### CODE REVIEW

**Comment by xu-cheng** [comment]
I would like to avoid formula rename with only minor name style changing. So I'm kinda :-1: this PR.

**Comment by mikemcquaid** [comment]
Here we're inconsistent with all other package managers (and have an alias already): https://kr.github.io/beanstalkd/download.html

**Comment by xu-cheng** [comment]
IMHO, alias should be enough. It's simple, robust and less likely to cause troubles.

**Comment by mikemcquaid** [comment]
@xu-cheng What would need to be done code-wise for you to be happy with simpler renames like this?

**Comment by xu-cheng** [comment]
I won't suggest to rename like this util we sort out:
* revert formula rename.
* rename a renamed formula.

And frankly, you cannot find simpler (hence more robust) solution than alias. For example, there are some underlying problems in formula rename which are hard(or impossible) to solve:
* It's hard to determine whether a cellar is pre-migration or a complete different formula/diy install. To the best, we can only guess. This is the same reason we have `--force` flag around to bypass these guesses in case we guess wrong.
* It's hard to have robust auto migration. We can not rely on `brew update` because there are thousands of things can break auto migration. Therefore, `brew migrate` will be required in many situations. And this is bad for CI staff(especially considering Homebrew is the default package manager for Travis CI on OS X).

**Comment by mikemcquaid** [comment]
:ok:. I think for me that means "we conservatively rename formulae for a while and get less conservative if we don't see any end-user bugs".

**Comment by apjanke** [comment]
Ping. Want to pursue this or just close it out as "sticking with the alias"?

**Comment by mikemcquaid** [comment]
@apjanke We've not seen end-uers bugs so let's persue this. @vladshablinsky could you open a new PR at homebrew-core for this? Thanks!

**Pull request closed without merging**
