### PR TITLE
ammonite-repl 0.5.7

### PR DESCRIPTION
**Pull request by schrepfler**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by apjanke** [comment]
Looks like the build is failing.

```

[0m[[33mwarn[0m] [0mStrategy 'discard' was applied to 3 files[0m
[0m[[33mwarn[0m] [0mStrategy 'rename' was applied to 2 files[0m
[0m[[0minfo[0m] [0mSHA-1: d1ba93b8f72c0071e09f8162d485c2aa961c79f6[0m
[0m[[0minfo[0m] [0mPackaging /private/tmp/ammonite-repl20160403-89712-1q00vtr/Ammonite-0.5.7/repl/target/scala-2.11/ammonite-repl-0.5.8-SNAPSHOT-2.11.8 ...[0m
[0m[[0minfo[0m] [0mDone packaging.[0m
[0m[[32msuccess[0m] [0mTotal time: 58 s, completed 03-Apr-2016 01:49:28[0m
Error: No such file or directory - repl/target/scala-2.11/ammonite-repl-0.5.7-2.11.8
```

(Those junk characters are from the build process emitting terminal control sequences. It would be nice if it wouldn't do that when not attached to a terminal.)

**Comment by schrepfler** [comment]
Ok, the binary distribution contains this file - Constants.scala which inside has val version = "0.5.8-SNAPSHOT”. I can either tweak the recipe to fix the version (but then we'd have to tweak it on any release) or @lihaoyi fixes the build and we get it in the next version. What is the preferred choice/policy?

**Comment by apjanke** [comment]
We'd prefer to have upstream fix the build and just pick up the fixed version. This looks like an error in this particular release's build, not an issue with OS X compatibility, so rather not change the formula to work around one bad build.

**Comment by apjanke** [comment]
I submitted the issue upstream. https://github.com/lihaoyi/Ammonite/issues/372. I'm going to close this out. Would you mind re-submitting when a fixed 0.5.7 or 0.5.8 is available?

We've done the core/formula split, so new formula update submissions should go to https://github.com/homebrew/homebrew-core.

**Comment by schrepfler** [comment]
Spoken with lihaoyi and refactored the formula to be just fetch of a binary (no bottle) and link (that's all that's needed really). This got merged into core, from next release we'll try to reference the github link explicitly rather than the short version of the link (as per Ammonite project homepage).

**Pull request closed without merging**
