### PR TITLE
mapserver 6.4.3

### LINKED ISSUE #46966: Impossible to install mapserver with PHP
Hi !

I would like to install Mapserver with tht PHP option in order to get the php_mapscript.so file. I do ```brew install mapserver --with-php''', but I get an error :

```==> Patching
patching file mapscript/python/setup.py
Hunk #1 FAILED at 32.
Hunk #2 FAILED at 149.
2 out of 3 hunks FAILED -- saving rejects to file mapscript/python/setup.py.rej
Error: Failure while executing: /usr/bin/patch -g 0 -f -p1```

I I don't want to install Mapserver from osgeo4mac, with which I had problems with the mapscript PHP and Python modules. I am working with Mac OS W 10.9.5.

### PR DESCRIPTION
**Pull request by DomT4**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

I'm not sure why I decided to try and get this done. All I wanted to do was successfully close #46966 and here I am an hour later and having rewritten most of the formula from scratch.

Closes #46966.

### CODE REVIEW

**Comment by DomT4** [comment]
@tdsmith Will owe you some more :cake: if you're feeling kind enough to check my Python changes here aren't completely wild :smile:.

**Comment by tdsmith** [comment]
wacky arms guy

**Comment by tdsmith** [comment]
:+1: if it works!

**Comment by DomT4** [comment]
Thanks! I'll report the Python library linkage dance upstream to see if they'll switch to `dynamic_lookup` on OS X, probably referencing your helpful blog on the subject given my own understanding there is limited.

I'm not quite sure _how_ this build is heading for a timeout, it takes a couple minutes locally to build. Will stick it in a clean VM later to see if I'm missing something from the formula.

**Comment by apjanke** [comment]
Closing this with the deprecation hammer. Re-submit on homebrew/core and maybe the build will work now that we've got test-bot running faster?

**Pull request closed without merging**
