### PR TITLE
dbus: rename from d-bus

### PR DESCRIPTION
**Pull request by vladshablinsky**
Needs to be merged when the bug is fixed. https://github.com/Homebrew/homebrew/issues/42965

### CODE REVIEW

**Comment by xu-cheng** [comment]
I would like to avoid formula rename with only minor name style changing. So I'm kinda :-1: this PR.

**Comment by mikemcquaid** [comment]
FWIW the Debian name: https://packages.debian.org/stable/mail/dbus

**Comment by apjanke** [comment]
Ping here too. Like beanstalkd, do we want to actually do anything here?

IMHO seems like the best thing to do in both cases might be to do the rename to match Debian and the other package managers, but add an alias for the old name so no command calls break.

**Comment by mikemcquaid** [comment]
Like beanstalkd: let's do the rename but @vladshablinsky could move it to homebrew-core. Thanks!

**Comment by UniqMartin** [comment]
Not a show-stopper, but let's not forget that a rename has also implications for formula options that reference the renamed formula, e.g. because it is an optional/recommended dependency.

**Comment by vladshablinsky** [comment]
@UniqMartin I'm not sure what you mean. I don't think we need change all the dependent formulae, it should work fine.

**Comment by UniqMartin** [comment]
@vladshablinsky Thanks, that's good and what I was hoping for. What I wanted to express is that, to pick `qt5` as an example, its optional `d-bus` dependency will sooner or later be changed to `dbus` (I guess we don't want to rely on `<oldname>` resolving to `<newname>` indefinitely) at which point we would also have to add `--with-d-bus` as a deprecated option that gets mapped to `--with-dbus`. (I don't think formula renames cover this, or do they?)

What I was implying with my comment: Is getting rid of a single hyphen in proportion to these changes?

**Comment by vladshablinsky** [comment]
@UniqMartin ah, I see. You're right, they don't cover the options renaming. I haven't thought about this case ever, and I'm not very good at Homebrew's options resolving process. It's a good note, though. I think it'll be possible to support resolving renamed options in a while, when renames are fully supported.

So, what do I do now? Rename the formula and add deprecated options?

**Comment by UniqMartin** [comment]
I'm not sure extending the rename support to options is what we want. If too many things happen automatically and options that don't appear in the formula file are magically recognized (because they belong to a renamed dependency), I think things can become pretty confusing. But it's definitely something to keep in mind when renaming formulae because of the tight coupling between optional/recommended dependencies and options automatically created for them we have in Homebrew.

> So, what do I do now? Rename the formula and add deprecated options?

To be honest, I'm not sure if I can answer that. @mikemcquaid and @apjanke seem to be in favor of the rename, @xu-cheng seems to be against it and I'm a bit undecided, but leaning towards @xu-cheng's side. However, *if* we move forward with this rename, eventually the options will need to be adjusted too. (This currently affects `emacs`, `pulseaudio`, `qt`, and `qt5`. They all have an optional `d-bus` dependency.) Sorry that I'm not able to provide a more definitive answer!

**Comment by mikemcquaid** [comment]
> So, what do I do now? Rename the formula and add deprecated options?

Yep, this is the right approach; we already have `deprecated_option` to handle this case.

**Comment by xu-cheng** [comment]
Just want to point out that although we can migrate all official formulae with `deprecated_option` it would still break third party formulae.

**Comment by vladshablinsky** [comment]
I've just thought about this: If it works with alias and both `--with-dbus` and `--with-d-bus` work fine, why wouldn't it work after rename?

**Comment by UniqMartin** [comment]
I guess I was successful in raising awareness that renaming a formula involves more than just changing its name, though that might have been obvious to some. Other than that, I don't care enough about `d-bus` (or `dbus`) specifically to want to veto this rename.

**Comment by mikemcquaid** [comment]
@UniqMartin A good point. It may be worth passing on this one then :

**Pull request closed without merging**
