### PR TITLE
shocco: pygments 2.1.1

### PR DESCRIPTION
**Pull request by fbrosson**

### CODE REVIEW

**Comment by mikemcquaid** [comment]
@fbrosson What's the advantage of the newer version? Are you sure we need a `revision` bump?

**Comment by fbrosson** [comment]
Well, there are several bug fixes and really a lot of improvements.

**Comment by mikemcquaid** [comment]
Ok but how do they effect Shocco specifically? I think regardless this shouldn't get a `revision` (which will force an upgrade/rebuild). Happy to ship this without, though.

**Comment by fbrosson** [comment]
Good question. I don't know how it affects Shocco. I would imagine that it affects it to some extent, since Pygments is its only resouce, but I don't know Shocco. I would say that the only users affected by a bump of `revision` are those who might benefit from the new Pygments. But, of course, I can revert the revision change if you prefer. Ah, my answer comes too late (the second build just finished).

**Comment by mikemcquaid** [comment]
If you don't know how it affects it: are you sure it doesn't cause any issues?

**Comment by fbrosson** [comment]
No, I don't know, because I don't use Shocco, so I couldn't even try it with the new Pygments version. Maybe the formula should have a `test do` (but I wouldn't know what to put there). Does Homebrew have statistics on downloads of bottles?

**Comment by mikemcquaid** [comment]
@fbrosson If you'd be able to add a `test do` block to run `shocco` on a `test.sh` script I think we can pull this (this may help: http://rtomayko.github.io/shocco/). If not I think we'll need to pass unless it's been tested. Thanks!

**Comment by fbrosson** [comment]
@mikemcquaid ok, I'l try to add a `test do` block. The link you gave is indeed a very interesting resource, as its source can be given to shocco and the results checked against its own source, since that page claims that:
> This page is the result of running shocco against its own source file.

I'll play with shocco a little bit before adding a test. (So don't worry if I don't submit anything before 1 or 2 days.) Thanks!

**Comment by mikemcquaid** [comment]
@fbrosson Sounds great, thanks!

**Comment by apjanke** [comment]
I'm closing this due to inactivity; it's been a couple months. If you'd still like to pursue this, feel free to re-open it at the new [`homebrew/core` repo](https://github.com/homebrew/homebrew-core) once you have a test written.

**Pull request closed without merging**
