### PR TITLE
cadubi 1.3.1

### PR DESCRIPTION
**Pull request by bfontaine**
This is an interactive program, we can’t test it more than with `--version`/`--help`.

### CODE REVIEW

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
The test is failing:
```
==> /usr/local/Cellar/cadubi/1.3/bin/cadubi --version
Using an array as a reference is deprecated at /usr/local/Cellar/cadubi/1.3/bin/cadubi line 347.
Using an array as a reference is deprecated at /usr/local/Cellar/cadubi/1.3/bin/cadubi line 353.
Using an array as a reference is deprecated at /usr/local/Cellar/cadubi/1.3/bin/cadubi line 354.
Using an array as a reference is deprecated at /usr/local/Cellar/cadubi/1.3/bin/cadubi line 855.
defined(@array) is deprecated at /usr/local/Cellar/cadubi/1.3/bin/cadubi line 895.
	(Maybe you should just omit the defined()?)
Unable to read terminal settings in GetControlChars at /usr/local/Cellar/cadubi/1.3/bin/cadubi line 461.
Error: cadubi: failed
<1> expected but was
<25>.
```

**Comment by bfontaine** [comment]
@BrewTestBot test this please.

**Comment by bfontaine** [comment]
The exact same command exits with `1` on El Cap but `0` on Mavericks & Yosemite :disappointed:

**Comment by DomT4** [comment]
Presuming there's not an actual functionality error on El Cap could you use `pipe_output` instead which doesn't check the exit code, AFAIK?

**Comment by bfontaine** [comment]
@DomT4 Yeah but it’d be great to understand why does it fail here.

**Comment by bfontaine** [comment]
Closing this for now; I’ll reopen on the new repo.

**Pull request closed without merging**
