### PR TITLE
sourcekittendaemon 0.1.3 (new formula)

### PR DESCRIPTION
**Pull request by mitsuse**
I wrote the formula for [SourceKittenDaemon][github-sourcekittendaemon], which is a server to provide completion feature for Swift in arbitrary text editor.

### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### New Formulae Submissions:

- [x] Does your submission pass
`brew audit --strict --online <formula>` (where `<formula>` is the name of the formula you're submitting)?
- [x] Have you built your formula locally prior to submission with `brew install <formula>`?

[github-sourcekittendaemon]: https://github.com/terhechte/SourceKittenDaemon

### CODE REVIEW

**Comment by apjanke** [comment]
This formula looks good, and I think we're good to merge it.

To clarify: what's the relationship between this and `sourcekitten`? The README says "This app uses the fantastic SourceKitten framework...". There's no `depends_on "sourcekitten"`, and this seems to work on its own, but I don't know this area well enough to confirm that. Does that mean that the necessary dependencies are bundled with SourceKittenDaemon? Just making sure there's not a run-time dependency or anything we're overlooking.

**Comment by cosmo0920** [comment]
> There's no depends_on "sourcekitten", and this seems to work on its own, but I don't know this area well enough to confirm that.

I'm not too familiar with `carthage`, although this Formula uses it on building time.
It seems that `sourcekitten` dependency is resolved by `carthage`: https://github.com/terhechte/SourceKittenDaemon/blob/master/Cartfile#L3
Should we clarify dependent carthage packages in Formula?

**Comment by apjanke** [comment]
> Should we clarify dependent carthage packages in Formula? 

Maybe. Probably.

In Homebrew, we like to get all the dependencies specified with specific versions inside the formula, so that every user installing it gets exactly the same version, and the dependencies are made explicit. You can see this done in formulae for Go and Java projects: For Go, we convert everything to `go_resource` items with specific versions. For Java – IIRC – we defer to Maven, but Maven specifies exact versions for its dependencies, so a Maven-driven build from a given formula version will use the same versions for all its source dependencies.

But Homebrew doesn't have a mechanism like this for Carthage, maybe since it's a younger dependency manager.

If we could convert those Carthage-driven dependencies to "vendored" dependencies with specific versions in the formula without too much work, that would be great. Or if Sourcekittendaemon's carthage config would lock it down to specifying specific versions, maybe we could just go with that. I'm not too familiar with Carthage myself, but my reading of [that config file](https://github.com/terhechte/SourceKittenDaemon/blob/c848558a39ddd685a525bb4ab2b2e5fb95d577b2/Cartfile#L3) is that it will pull down the latest (possibly "HEAD" and not "stable") versions of its dependencies, so the result of a build with that formula could vary over time, which is counter to how Homebrew manages stuff.

I'd like to hear from other Homebrew maintainers on this. Especially if anybody's worked with Carthage specifically.

**Comment by cosmo0920** [comment]
> my reading of that config file is that it will pull down the latest (possibly "HEAD" and not "stable") versions of its dependencies,

Carthage has a ability to pull stable version of packages like bundler: https://github.com/terhechte/SourceKittenDaemon/blob/c848558a39ddd685a525bb4ab2b2e5fb95d577b2/Cartfile.resolved
So, carthage can lock down specific stable versions and VCS' specific revisions.

> I'd like to hear from other Homebrew maintainers on this.

Yeah. I think so, too.

**Comment by apjanke** [comment]
Okay, cool. I think we wouldn't want to pull this formula in as is, but we could fix the versions by just including a patch in the formula to add specific numbers to that cartfile. Or, preferably, if upstream would lock it down by specifying exact releases in the cartfile for their tagged releases, which would benefit non-Homebrew users as well, and keep the formula simpler. (Downside of the patch approach is that it would require manual review/editing on each version bump, and Homebrew's install could diverge from the default install using the upstream distribution.)

**Comment by mikemcquaid** [comment]
@apjanke I think I'd want to see upstream accept this approach before we patch it ourselves.

**Comment by mitsuse** [comment]
Thanks everyone.

This formula uses `Carthage` not to check out frameworks but to build them.
The versions of dependencies are recoreded in [`Cartfile.resolved`][github-sourcekittendaemon-cartfile_resolved] and their source files are included as git-submodules in the repository.

> apjanke wrote:
> 
> Or, preferably, if upstream would lock it down by specifying exact releases in the cartfile for their tagged releases, which would benefit non-Homebrew users as well, and keep the formula simpler.

This approach seems to be better than the patch-based approach, especially for developers of Homebrew and SourceKittenDaemon.

I will submit a pull-request to SourceKittenDaemon to use tagged versions.
Specifically, `Cartfile.resolve` will change as follow:

```diff
diff --git a/Cartfile b/Cartfile
index 84dc9a2..bff9e23 100644
--- a/Cartfile
+++ b/Cartfile
@@ -1,3 +1,3 @@
-github "izqui/taylor" "master"
-github "Carthage/Commandant" "master"
-github "jpsim/SourceKitten"
+github "izqui/taylor" == 0.3.2
+github "Carthage/Commandant" == 0.7.0
+github "jpsim/SourceKitten" == 0.11.0
```

Please close if there is not any other problem, and I will create a new pull-request as soon as it is ready.

[github-sourcekittendaemon-cartfile_resolved]: https://github.com/terhechte/SourceKittenDaemon/blob/0.1.3/Cartfile.resolved

**Comment by apjanke** [comment]
Ping!

Closing this out since legacy-homebrew is deprecated. If upstream makes a tagged release, feel free to re-open on the new [`homebrew/core` repo](https://github.com/homebrew/homebrew-core) and we'll merge it.

**Pull request closed without merging**
