### PR TITLE
rtorrent/libtorrent: remove extraneous build dependencies

### PR DESCRIPTION
**Pull request by tzudot**
### All Submissions:

- [x] Have you followed the guidelines in our [Contributing](https://github.com/Homebrew/homebrew/blob/master/.github/CONTRIBUTING.md) document?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/Homebrew/homebrew/pulls) for the same update/change?

### CODE REVIEW

**Comment by luxus** [comment]
it build fine.. 

after building i got a message about different compiler and xmlrpc-c (not build with clang)

when i start rtorrent it  crash after some seconds

`○ → rtorrent
Caught Segmentation fault, dumping stack:
0   rtorrent                            0x0000000100713a4c _Z8do_panici + 233
1   libsystem_platform.dylib            0x00007fff983bbeaa _sigtramp + 26
2   ???                                 0x00007fff5f4f3be8 0x0 + 140734792416232
3   libtorrent.19.dylib                 0x0000000100916852 _ZNSt6vectorIN7torrent9ChunkPartESaIS1_EE6insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EERKS1_ + 88
4   libtorrent.19.dylib                 0x0000000100915ff5 _ZN7torrent5Chunk9push_backENS_9ChunkPart11mapped_typeERKNS_11MemoryChunkE + 101
5   libtorrent.19.dylib                 0x00000001008fd0b4 _ZN7torrent8FileList12create_chunkEyji + 248
6   libtorrent.19.dylib                 0x00000001009174e5 _ZN7torrent9ChunkList3getEji + 275
7   libtorrent.19.dylib                 0x0000000100942504 _ZN7torrent18PeerConnectionBase13load_up_chunkEv + 162
8   libtorrent.19.dylib                 0x0000000100947eb3 _ZN7torrent14PeerConnectionILNS_8Download14ConnectionTypeE1EE11event_writeEv + 253
9   libtorrent.19.dylib                 0x00000001008f063f _ZN7torrent10PollKQueue7performEv + 285
10  libtorrent.19.dylib                 0x00000001009158f8 _ZN7torrent11thread_base10event_loopEPS0_ + 422
11  rtorrent                            0x0000000100713474 main + 13437
12  libdyld.dylib                       0x00007fff94fa05ad start + 1
Abort trap: 6`

**Comment by tzudot** [comment]
@luxus I am seeing the error only on `El Capitan` when built using `--with-xmlrpc-c`. I'll check the stack trace and report it upstream. Also, does it work if you do not include `xmlrpc-c` during build and in the confiuration file?

@DomT4 should I increase the delay in `test do` block for possible failures on other platforms? By the way, I don't see an issue if built without `xmlrpc`.

**Comment by DomT4** [comment]
> should I increase the delay in test do block for possible failures on other platforms? By the way, I don't see an issue if built without xmlrpc-c.

I wouldn't worry about the timing if it's passing CI. Any idea how widely used the `xmlrpc-c` option is? Any chance of a test for `libtorrent` as well at all?

**Comment by tzudot** [comment]
`xmlrpc-c` is used by various web clients, and also, command line tools such as `pyrocore`. A test for `libtorrent` can be a simple `#include` and compile but I wonder if it is of any help.

**Comment by tzudot** [comment]
Filed an upstream [issue](https://github.com/rakshasa/rtorrent/issues/400) about the crash when built with `xmlrpc-c` on Mac OS X 10.11.3.

**Comment by tzudot** [comment]
The issue file upstream has been closed on the account that there is a possible fix in git HEAD.

As for this PR, it has nothing to do with the failure of `rtorrent` when used with `xmlrpc-c` (optional) but fixing `rtorrent` Homebrew build, and can be merged. I'll check on `rtorrent` git HEAD and if possible patches which can be applied to resolve `xmlrpc-c` as well.

**Comment by apjanke** [comment]
Closing this due to inactivity. If you'd still like to pursue this, feel free to respond to the previous comments/questions and re-open on the new [`homebrew/core` repo](https://github.com/homebrew/homebrew-core).

Or just wait until the next upstream release is out.

**Comment by ilovezfs** [comment]
These are actually now boneyarded.

**Comment by apjanke** [comment]
Nevermind about the re-submission then. Sorry for not noticing that.

**Pull request closed without merging**
